"""
Repository rule that resolves the absolute filesystem path of a gcc toolchain
http_archive at fetch-time. This is necessary because cxx_builtin_include_directories
must use absolute paths to match what GCC reports during compilation.

The problem: GCC resolves include paths to absolute paths like
  /home/user/.cache/bazel/_bazel_user/HASH/external/REPO/lib/gcc/.../include
But cc_toolchain_config can only see execution-root-relative paths like
  external/REPO/lib/gcc/.../include
These don't match, causing "undeclared inclusion" errors.

The solution: Use a repository_rule to resolve the absolute path of the
gcc_toolchain repo at fetch time, write it to a .bzl file, and load it
in the BUILD file that defines the cc_toolchain_config.

This follows the same pattern used by toolchains_llvm (absolute_paths mode)
which calls rctx.path(Label("@repo//:BUILD.bazel")).dirname to get the
real filesystem path.
"""

def _gcc_toolchain_config_impl(rctx):
    # The name of the gcc toolchain repository whose path we want to resolve.
    repo_name = rctx.attr.gcc_repo_name

    # Resolve the absolute filesystem path of the gcc toolchain repository.
    # Label("@<repo>//:BUILD") points to the BUILD file inside the
    # http_archive repo; .dirname gives us the repo root directory.
    gcc_repo_label = Label("@" + repo_name + "//:BUILD")
    gcc_repo_path = str(rctx.path(gcc_repo_label).dirname)

    # Write the resolved path into a .bzl file that can be loaded by BUILD files.
    rctx.file("defs.bzl", content = """\
# AUTO-GENERATED by gcc_toolchain_config repository rule.
# Do not edit manually.

# Absolute filesystem path to the {repo_name} repository root.
# This path is resolved at repository-fetch time and will be something like:
#   /home/user/.cache/bazel/_bazel_user/HASH/external/_main~_repo_rules~{repo_name}
GCC_TOOLCHAIN_ABSOLUTE_PATH = "{path}"
""".format(repo_name = repo_name, path = gcc_repo_path))

    # Create a minimal BUILD file so this is a valid Bazel package.
    rctx.file("BUILD.bazel", content = """\
# This repository provides the resolved absolute path of @{repo_name}.
# Load @{config_name}//:defs.bzl to access GCC_TOOLCHAIN_ABSOLUTE_PATH.
""".format(repo_name = repo_name, config_name = rctx.name))

gcc_toolchain_config = repository_rule(
    implementation = _gcc_toolchain_config_impl,
    attrs = {
        "gcc_repo_name": attr.string(
            mandatory = True,
            doc = "The name of the gcc toolchain http_archive repository to resolve.",
        ),
    },
    doc = """
Resolves the absolute filesystem path of a gcc toolchain repository
and makes it available as a Starlark constant. This is needed for
cxx_builtin_include_directories which must match the absolute paths
that GCC reports during compilation.
""",
)
